version: "3.7"

x-flink-common: &flink-common
    build: 
      context: ./flink
    image: sc/flink-iceberg
    restart: always
    environment:
      FLINK_PROPERTIES: |-
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        classloader.check-leaked-classloader: false
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints-dir
        state.savepoints.dir: file:///tmp/flink-savepoints-dir
        restart-strategy.fixed-delay.attempts: 3
        restart-strategy.fixed-delay.delay: 10s
    volumes:
      - /Users/binh/projects/iceberg/flink/v1.12/flink-runtime/build/libs/iceberg-flink-1.12-runtime-0.13.0-SNAPSHOT.jar:/opt/flink/lib/iceberg-flink-1.12-runtime-0.13.0-SNAPSHOT.jar
      - ./.local/flink/checkpoints-dir:/tmp/flink-checkpoints-dir
      - ./.local/flink/savepoints-dir:/tmp/flink-savepoints-dir
      - ./.local/iceberg/warehouse/:/tmp/iceberg/warehouse/
      - ./flink/conf/flink-sql.yaml:/opt/flink/conf/flink-sql.yaml

services:
  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "cdc-sink:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
      - 9094:9094

  # Hive Meatastore
  hive:
    build: 
      context: ./hive-metastore
    ports:
      - "9083:9083"
      - "10000:10000"
      - "10002:10002"
    links:
      - "hive-postgres:postgres"

  hive-postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore

  # Source Mysql DB
  mysql:
    image: mysql:8.0.19
    ports: 
      - 3306:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: demo
      MYSQL_PASSWORD: demo
      MYSQL_USER: demo
      MYSQL_ROOT_PASSWORD: demo


  # Flink Cluster
  jobmanager: 
    <<: *flink-common
    command: jobmanager
    ports:
      - 8081:8081
  taskmanager:
    <<: *flink-common
    command: taskmanager
    depends_on:
      - jobmanager
  adhoc:
    <<: *flink-common
    command: adhoc
    depends_on:
      - jobmanager

